language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    CODECOV_TOKEN='c5b41c03-dd3d-4d6b-b960-450a44052b5f'

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - vitalijvictor@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

- name: Codecov
    uses: codecov/codecov-action@v2.1.0

steps:
  - uses: actions/checkout@master
  - uses: codecov/codecov-action@v2
    with:
      token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      files: ./coverage1.xml,./coverage2.xml # optional
      flags: unittests # optional
      name: codecov-umbrella # optional
      fail_ci_if_error: true # optional (default = false)
      verbose: true # optional (default = false)
