language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    CODECOV_TOKEN='c5b41c03-dd3d-4d6b-b960-450a44052b5f'

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - vitalijvictor@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
